<?php
/**
 * ModelInclude
 *
 * PHP version 5
 *
 * @category Class
 * @package  BigCommerce\Api\V3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server to Server Checkout API
 *
 * ### Checkout Allows for a checkout to be created from an existing cart using BigCommerce checkout logic. The existing BigCommerce front end cart/checkout can be bypassed.  Notes: - checkoutId is the same as the cartId.
 *
 * OpenAPI spec version: 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BigCommerce\Api\V3\Model\Checkout;
use \BigCommerce\Api\V3\ObjectSerializer;

/**
 * ModelInclude Class Doc Comment
 *
 * @category Class
 * @package  BigCommerce\Api\V3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ModelInclude
{
    /**
     * Possible values of this enum
     */
    const CONSIGNMENTSAVAILABLE_SHIPPING_OPTIONS = 'consignments.availableShippingOptions';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONSIGNMENTSAVAILABLE_SHIPPING_OPTIONS,
        ];
    }
}


